--<ScriptOptions statementTerminator=";"/>

CREATE TABLE HIBERNATE_SEQUENCES (
		SEQUENCE_NAME VARCHAR(255),
		SEQUENCE_NEXT_HI_VALUE INTEGER
	);

	
CREATE TABLE BOX_AND_ROLE (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		ROLE VARCHAR(255),
		BOX BIGINT
	);

CREATE TABLE SOFTWARE_FILES_TO_UPLOAD (
		SOFTWARE BIGINT NOT NULL,
		FILES_TO_UPLOAD VARCHAR(255)
	);

CREATE TABLE KKV (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		KEY VARCHAR(255),
		KGROUP VARCHAR(255),
		VALUE VARCHAR(255),
		OWNER BIGINT
	);

CREATE TABLE SOFTWARE (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		CODE_TO_EXECUTE CLOB(2147483647),
		CONFIG_CONTENT CLOB(2147483647),
		NAME VARCHAR(255) NOT NULL,
		OSTYPE VARCHAR(255) NOT NULL,
		PREFERRED_FORMAT VARCHAR(255)
	);

CREATE TABLE ROLE (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		NAME VARCHAR(255) NOT NULL
	);

CREATE TABLE PKSOURCE (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		EXT_NO_DOT VARCHAR(255),
		FILE_MD5 VARCHAR(255) NOT NULL,
		LENGTH BIGINT,
		MIME_TYPE VARCHAR(255),
		ORIGIN_FROM VARCHAR(255),
		PKNAME VARCHAR(255)
	);

CREATE TABLE CLUSTER_HISTORY (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		BOX_GROUP BIGINT
	);

CREATE TABLE BOX_HISTORY (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		LOG CLOB(2147483647),
		READED BOOLEAN NOT NULL,
		SUCCESS BOOLEAN NOT NULL,
		BOX BIGINT,
		CLUSTER_HISTORY BIGINT,
		SOFTWARE BIGINT
	);

CREATE TABLE BLOBINDB (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		BLOB CLOB(2147483647),
		NAME VARCHAR(255)
	);

CREATE TABLE BOX_BOX_GROUPS (
		BOXES BIGINT NOT NULL,
		BOX_GROUPS BIGINT NOT NULL
	);

CREATE TABLE BOX (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		COMMA_SEP_IPS VARCHAR(255),
		COMMA_SEP_PORTS VARCHAR(255),
		DESCRIPTION VARCHAR(255),
		DNS_SERVER VARCHAR(255),
		HOSTNAME VARCHAR(255),
		IP VARCHAR(255) NOT NULL,
		KEY_FILE_PATH VARCHAR(255),
		NAME VARCHAR(255),
		OS_TYPE VARCHAR(255) NOT NULL,
		PORT INTEGER NOT NULL,
		SSH_USER VARCHAR(255)
	);

CREATE TABLE PERSON (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		ACCOUNT_NON_EXPIRED BOOLEAN NOT NULL,
		ACCOUNT_NON_LOCKED BOOLEAN NOT NULL,
		AVATAR VARCHAR(255),
		CREDENTIALS_NON_EXPIRED BOOLEAN NOT NULL,
		EMAIL VARCHAR(255) NOT NULL,
		EMAIL_VERIFIED BOOLEAN NOT NULL,
		ENABLED BOOLEAN NOT NULL,
		GENDER VARCHAR(255),
		LEVEL INTEGER NOT NULL,
		MOBILE VARCHAR(255),
		MOBILE_VERIFIED BOOLEAN NOT NULL,
		NAME VARCHAR(255),
		PASSWORD VARCHAR(255)
	);

CREATE TABLE PERSON_ROLES (
		PERSON BIGINT NOT NULL,
		ROLES BIGINT NOT NULL
	);

CREATE TABLE BOX_GROUP (
		ID BIGINT NOT NULL,
		ARCHIVED BOOLEAN NOT NULL,
		CREATED_AT TIMESTAMP,
		VERSION INTEGER NOT NULL,
		CONFIG_CONTENT CLOB(2147483647),
		DNS_SERVER VARCHAR(255),
		NAME VARCHAR(255)
	);

CREATE UNIQUE INDEX PRIMARY_KEY_A ON BOX_HISTORY (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_2 ON ROLE (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_12 ON KKV (ID ASC);

CREATE INDEX FK_OGPDTISIB6VVL8J0OP9DTY19O_INDEX_9 ON SOFTWARE_FILES_TO_UPLOAD (SOFTWARE ASC);

CREATE UNIQUE INDEX UK_IEX44YVW0L9IJT0OAH2JUTDSH_INDEX_8 ON PKSOURCE (FILE_MD5 ASC);

CREATE INDEX FK_EAD5A39CYL5VLYTMYNHRF1AMJ_INDEX_6 ON CLUSTER_HISTORY (BOX_GROUP ASC);

CREATE INDEX FK_7KMU12BW4MKEBHI4REUNP7KS4_INDEX_1 ON KKV (OWNER ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_BLOBINDB_ID ON BLOBINDB (ID ASC);

CREATE UNIQUE INDEX UK_4NKGPTL88FXGNEG8EXHAIFRMJ_INDEX_8 ON PKSOURCE (PKNAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1D ON BOX_GROUP (ID ASC);

CREATE UNIQUE INDEX UK_TBR9H21C6UWGUWHA82R5FBHJH_INDEX_6 ON BLOBINDB (NAME ASC);

CREATE UNIQUE INDEX UK_F85XLT5RSD3FI6CIX1DUEQSS0_INDEX_E ON BOX_AND_ROLE (BOX ASC, ROLE ASC);

CREATE UNIQUE INDEX UK_FWMWI44U55BO4RVWSV0CLN012_INDEX_8 ON PERSON (EMAIL ASC);

CREATE INDEX FK_FV7DV2XO3YH65WVCOW1RDGV1I_INDEX_A ON BOX_HISTORY (CLUSTER_HISTORY ASC);

CREATE UNIQUE INDEX UK_P0WR4VFYR2LYIFM8AVI67MQW5_INDEX_8 ON PERSON (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E ON BOX_AND_ROLE (ID ASC);

CREATE UNIQUE INDEX UK_NELSROEK3WBIREPDOEMHUOPTX_INDEX_1 ON KKV (KGROUP ASC, KEY ASC, VALUE ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_4 ON BOX_BOX_GROUPS (BOXES ASC, BOX_GROUPS ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1 ON BOX (ID ASC);

CREATE INDEX FK_7F9130DSLI9TT4NRM71ISUB2A_INDEX_A ON PERSON_ROLES (ROLES ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_7 ON SOFTWARE (ID ASC);

CREATE UNIQUE INDEX UK_FMT6T8RFJ6JX2M6VBYQP421DG_INDEX_7 ON SOFTWARE (NAME ASC, OSTYPE ASC);

CREATE UNIQUE INDEX UK_JCL7IKHLYXC1R9KC1PQRIIDS0_INDEX_8 ON PERSON (MOBILE ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8 ON PERSON (ID ASC);

CREATE UNIQUE INDEX UK_2D2DG1EOB54HFN05QU0UAYPMX_INDEX_1 ON BOX (IP ASC);

CREATE UNIQUE INDEX UK_8SEWWNPAMNGI6B1DWAA88ASKK_INDEX_2 ON ROLE (NAME ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_87 ON PKSOURCE (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_AE ON PERSON_ROLES (PERSON ASC, ROLES ASC);

CREATE INDEX FK_IPMDGKNGUE418YHBWPCONR86I_INDEX_4 ON BOX_BOX_GROUPS (BOX_GROUPS ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_61 ON CLUSTER_HISTORY (ID ASC);

CREATE INDEX FK_5MMUCQSJ05B0INX1EW4TR2MGG_INDEX_A ON BOX_HISTORY (BOX ASC);

CREATE INDEX FK_DT3M8S0F08OPYD144VWJJAQA7_INDEX_A ON BOX_HISTORY (SOFTWARE ASC);

ALTER TABLE ROLE ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID);

ALTER TABLE SOFTWARE ADD CONSTRAINT PRIMARY_KEY_7 UNIQUE (ID);

ALTER TABLE PERSON ADD CONSTRAINT PRIMARY_KEY_8 UNIQUE (ID);

ALTER TABLE SOFTWARE ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY (ID);

ALTER TABLE PERSON ADD CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID);

ALTER TABLE BLOBINDB ADD CONSTRAINT CONSTRAINT_6 PRIMARY KEY (ID);

ALTER TABLE BOX_BOX_GROUPS ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY (BOXES, BOX_GROUPS);

ALTER TABLE BOX ADD CONSTRAINT PRIMARY_KEY_1 UNIQUE (ID);

ALTER TABLE KKV ADD CONSTRAINT CONSTRAINT_12 PRIMARY KEY (ID);

ALTER TABLE BOX_GROUP ADD CONSTRAINT CONSTRAINT_1D PRIMARY KEY (ID);

ALTER TABLE PERSON_ROLES ADD CONSTRAINT CONSTRAINT_AE PRIMARY KEY (PERSON, ROLES);

ALTER TABLE ROLE ADD CONSTRAINT PRIMARY_KEY_2 UNIQUE (ID);

ALTER TABLE BOX_AND_ROLE ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY (ID);

ALTER TABLE PKSOURCE ADD CONSTRAINT CONSTRAINT_87 PRIMARY KEY (ID);

ALTER TABLE BOX_GROUP ADD CONSTRAINT PRIMARY_KEY_1D UNIQUE (ID);

ALTER TABLE BOX_HISTORY ADD CONSTRAINT CONSTRAINT_A PRIMARY KEY (ID);

ALTER TABLE BOX ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY (ID);

ALTER TABLE CLUSTER_HISTORY ADD CONSTRAINT PRIMARY_KEY_61 UNIQUE (ID);

ALTER TABLE CLUSTER_HISTORY ADD CONSTRAINT CONSTRAINT_61 PRIMARY KEY (ID);

ALTER TABLE BOX_HISTORY ADD CONSTRAINT FK_FV7DV2XO3YH65WVCOW1RDGV1I FOREIGN KEY (CLUSTER_HISTORY)
	REFERENCES CLUSTER_HISTORY (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE SOFTWARE_FILES_TO_UPLOAD ADD CONSTRAINT FK_OGPDTISIB6VVL8J0OP9DTY19O FOREIGN KEY (SOFTWARE)
	REFERENCES SOFTWARE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PERSON_ROLES ADD CONSTRAINT FK_85DXLECI0BHW3HBDCD0TIWPWY FOREIGN KEY (PERSON)
	REFERENCES PERSON (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE BOX_AND_ROLE ADD CONSTRAINT FK_2960VV9FWG8E8S8U7Y10AXVXI FOREIGN KEY (BOX)
	REFERENCES BOX (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE BOX_BOX_GROUPS ADD CONSTRAINT FK_IPMDGKNGUE418YHBWPCONR86I FOREIGN KEY (BOX_GROUPS)
	REFERENCES BOX_GROUP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE BOX_HISTORY ADD CONSTRAINT FK_5MMUCQSJ05B0INX1EW4TR2MGG FOREIGN KEY (BOX)
	REFERENCES BOX (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE KKV ADD CONSTRAINT FK_7KMU12BW4MKEBHI4REUNP7KS4 FOREIGN KEY (OWNER)
	REFERENCES PERSON (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE PERSON_ROLES ADD CONSTRAINT FK_7F9130DSLI9TT4NRM71ISUB2A FOREIGN KEY (ROLES)
	REFERENCES ROLE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE BOX_HISTORY ADD CONSTRAINT FK_DT3M8S0F08OPYD144VWJJAQA7 FOREIGN KEY (SOFTWARE)
	REFERENCES SOFTWARE (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE BOX_BOX_GROUPS ADD CONSTRAINT FK_IWX26E81FWHXKK1G39CQ1BUJ1 FOREIGN KEY (BOXES)
	REFERENCES BOX (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE CLUSTER_HISTORY ADD CONSTRAINT FK_EAD5A39CYL5VLYTMYNHRF1AMJ FOREIGN KEY (BOX_GROUP)
	REFERENCES BOX_GROUP (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

